#ifndef TINYRNN_STANDALONE_GUARD_d6b80c7dd9ae4f1e887fe064c13ec7d32840a49a15066a4f58d40a912a2f7bb3
#define TINYRNN_STANDALONE_GUARD_d6b80c7dd9ae4f1e887fe064c13ec7d32840a49a15066a4f58d40a912a2f7bb3

extern float kMemory[];
const int kMemorySize = 8864515;

extern float kOutputs[];
const int kOutputsSize = 64;

#ifdef __cplusplus
extern "C"  {
#endif
    void feed_0(const float *input, float *output, float *x);
    void feed_1(const float *input, float *output, float *x);
    void feed_2(const float *input, float *output, float *x);
    void feed_3(const float *input, float *output, float *x);
    void feed_4(const float *input, float *output, float *x);
    void feed_5(const float *input, float *output, float *x);
    void feed_6(const float *input, float *output, float *x);
    void feed_7(const float *input, float *output, float *x);
    void feed_8(const float *input, float *output, float *x);
    void feed_9(const float *input, float *output, float *x);
    void feed_10(const float *input, float *output, float *x);
    void feed_11(const float *input, float *output, float *x);
    void feed_12(const float *input, float *output, float *x);
    void feed_13(const float *input, float *output, float *x);
    void feed_14(const float *input, float *output, float *x);
    void feed_15(const float *input, float *output, float *x);
    void feed_16(const float *input, float *output, float *x);
    void feed_17(const float *input, float *output, float *x);
    void feed_18(const float *input, float *output, float *x);
    void feed_19(const float *input, float *output, float *x);
    void feed_20(const float *input, float *output, float *x);
    void feed_21(const float *input, float *output, float *x);
    void feed_22(const float *input, float *output, float *x);
    void feed_23(const float *input, float *output, float *x);
    void feed_24(const float *input, float *output, float *x);
    void feed_25(const float *input, float *output, float *x);
    void feed_26(const float *input, float *output, float *x);
    void feed_27(const float *input, float *output, float *x);
    void feed_28(const float *input, float *output, float *x);
    void feed_29(const float *input, float *output, float *x);
    void feed_30(const float *input, float *output, float *x);
    void feed_31(const float *input, float *output, float *x);
    void feed_32(const float *input, float *output, float *x);
    void feed_33(const float *input, float *output, float *x);
    void feed_34(const float *input, float *output, float *x);
    void feed_35(const float *input, float *output, float *x);
    void feed_36(const float *input, float *output, float *x);
    void feed_37(const float *input, float *output, float *x);
    void feed_38(const float *input, float *output, float *x);
    void feed_39(const float *input, float *output, float *x);
    void feed_40(const float *input, float *output, float *x);
    void feed_41(const float *input, float *output, float *x);
    void feed_42(const float *input, float *output, float *x);
    void feed_43(const float *input, float *output, float *x);
    void feed_44(const float *input, float *output, float *x);
    void feed_45(const float *input, float *output, float *x);
    void feed_46(const float *input, float *output, float *x);
    void feed_47(const float *input, float *output, float *x);
    void feed_48(const float *input, float *output, float *x);
    void feed_49(const float *input, float *output, float *x);
    void feed_50(const float *input, float *output, float *x);
    void feed_51(const float *input, float *output, float *x);
    void feed_52(const float *input, float *output, float *x);
    void feed_53(const float *input, float *output, float *x);
    void feed_54(const float *input, float *output, float *x);
    void feed_55(const float *input, float *output, float *x);
    void feed_56(const float *input, float *output, float *x);
    void feed_57(const float *input, float *output, float *x);
    void feed_58(const float *input, float *output, float *x);
    void feed_59(const float *input, float *output, float *x);
    void feed_60(const float *input, float *output, float *x);
    void feed_61(const float *input, float *output, float *x);
    void feed_62(const float *input, float *output, float *x);
    void feed_63(const float *input, float *output, float *x);
    void feed_64(const float *input, float *output, float *x);
    void feed_65(const float *input, float *output, float *x);
    void feed_66(const float *input, float *output, float *x);
    void feed_67(const float *input, float *output, float *x);
    void feed_68(const float *input, float *output, float *x);
    void feed_69(const float *input, float *output, float *x);

    void train_0(const float *rate, const float *target, float *x);
    void train_1(const float *rate, const float *target, float *x);
    void train_2(const float *rate, const float *target, float *x);
    void train_3(const float *rate, const float *target, float *x);
    void train_4(const float *rate, const float *target, float *x);
    void train_5(const float *rate, const float *target, float *x);
    void train_6(const float *rate, const float *target, float *x);
    void train_7(const float *rate, const float *target, float *x);
    void train_8(const float *rate, const float *target, float *x);
    void train_9(const float *rate, const float *target, float *x);
    void train_10(const float *rate, const float *target, float *x);
    void train_11(const float *rate, const float *target, float *x);
    void train_12(const float *rate, const float *target, float *x);
    void train_13(const float *rate, const float *target, float *x);
    void train_14(const float *rate, const float *target, float *x);
    void train_15(const float *rate, const float *target, float *x);
    void train_16(const float *rate, const float *target, float *x);
    void train_17(const float *rate, const float *target, float *x);
    void train_18(const float *rate, const float *target, float *x);
    void train_19(const float *rate, const float *target, float *x);
    void train_20(const float *rate, const float *target, float *x);
    void train_21(const float *rate, const float *target, float *x);
    void train_22(const float *rate, const float *target, float *x);
    void train_23(const float *rate, const float *target, float *x);
    void train_24(const float *rate, const float *target, float *x);
    void train_25(const float *rate, const float *target, float *x);
    void train_26(const float *rate, const float *target, float *x);
    void train_27(const float *rate, const float *target, float *x);
    void train_28(const float *rate, const float *target, float *x);
    void train_29(const float *rate, const float *target, float *x);
    void train_30(const float *rate, const float *target, float *x);
    void train_31(const float *rate, const float *target, float *x);
    void train_32(const float *rate, const float *target, float *x);
    void train_33(const float *rate, const float *target, float *x);
    void train_34(const float *rate, const float *target, float *x);
    void train_35(const float *rate, const float *target, float *x);
    void train_36(const float *rate, const float *target, float *x);
    void train_37(const float *rate, const float *target, float *x);
    void train_38(const float *rate, const float *target, float *x);
    void train_39(const float *rate, const float *target, float *x);
    void train_40(const float *rate, const float *target, float *x);
    void train_41(const float *rate, const float *target, float *x);
    void train_42(const float *rate, const float *target, float *x);
    void train_43(const float *rate, const float *target, float *x);
    void train_44(const float *rate, const float *target, float *x);
    void train_45(const float *rate, const float *target, float *x);
    void train_46(const float *rate, const float *target, float *x);
    void train_47(const float *rate, const float *target, float *x);
    void train_48(const float *rate, const float *target, float *x);
    void train_49(const float *rate, const float *target, float *x);
    void train_50(const float *rate, const float *target, float *x);
    void train_51(const float *rate, const float *target, float *x);
    void train_52(const float *rate, const float *target, float *x);
    void train_53(const float *rate, const float *target, float *x);
    void train_54(const float *rate, const float *target, float *x);
    void train_55(const float *rate, const float *target, float *x);
    void train_56(const float *rate, const float *target, float *x);
    void train_57(const float *rate, const float *target, float *x);
    void train_58(const float *rate, const float *target, float *x);
    void train_59(const float *rate, const float *target, float *x);
    void train_60(const float *rate, const float *target, float *x);
    void train_61(const float *rate, const float *target, float *x);
    void train_62(const float *rate, const float *target, float *x);
    void train_63(const float *rate, const float *target, float *x);
    void train_64(const float *rate, const float *target, float *x);
    void train_65(const float *rate, const float *target, float *x);
    void train_66(const float *rate, const float *target, float *x);
    void train_67(const float *rate, const float *target, float *x);
    void train_68(const float *rate, const float *target, float *x);
    void train_69(const float *rate, const float *target, float *x);
    void train_70(const float *rate, const float *target, float *x);
#ifdef __cplusplus
}
#endif

inline void GoDeeperFeed(const float *inputs)
{
    feed_0(inputs, kOutputs, kMemory);
    feed_1(inputs, kOutputs, kMemory);
    feed_2(inputs, kOutputs, kMemory);
    feed_3(inputs, kOutputs, kMemory);
    feed_4(inputs, kOutputs, kMemory);
    feed_5(inputs, kOutputs, kMemory);
    feed_6(inputs, kOutputs, kMemory);
    feed_7(inputs, kOutputs, kMemory);
    feed_8(inputs, kOutputs, kMemory);
    feed_9(inputs, kOutputs, kMemory);
    feed_10(inputs, kOutputs, kMemory);
    feed_11(inputs, kOutputs, kMemory);
    feed_12(inputs, kOutputs, kMemory);
    feed_13(inputs, kOutputs, kMemory);
    feed_14(inputs, kOutputs, kMemory);
    feed_15(inputs, kOutputs, kMemory);
    feed_16(inputs, kOutputs, kMemory);
    feed_17(inputs, kOutputs, kMemory);
    feed_18(inputs, kOutputs, kMemory);
    feed_19(inputs, kOutputs, kMemory);
    feed_20(inputs, kOutputs, kMemory);
    feed_21(inputs, kOutputs, kMemory);
    feed_22(inputs, kOutputs, kMemory);
    feed_23(inputs, kOutputs, kMemory);
    feed_24(inputs, kOutputs, kMemory);
    feed_25(inputs, kOutputs, kMemory);
    feed_26(inputs, kOutputs, kMemory);
    feed_27(inputs, kOutputs, kMemory);
    feed_28(inputs, kOutputs, kMemory);
    feed_29(inputs, kOutputs, kMemory);
    feed_30(inputs, kOutputs, kMemory);
    feed_31(inputs, kOutputs, kMemory);
    feed_32(inputs, kOutputs, kMemory);
    feed_33(inputs, kOutputs, kMemory);
    feed_34(inputs, kOutputs, kMemory);
    feed_35(inputs, kOutputs, kMemory);
    feed_36(inputs, kOutputs, kMemory);
    feed_37(inputs, kOutputs, kMemory);
    feed_38(inputs, kOutputs, kMemory);
    feed_39(inputs, kOutputs, kMemory);
    feed_40(inputs, kOutputs, kMemory);
    feed_41(inputs, kOutputs, kMemory);
    feed_42(inputs, kOutputs, kMemory);
    feed_43(inputs, kOutputs, kMemory);
    feed_44(inputs, kOutputs, kMemory);
    feed_45(inputs, kOutputs, kMemory);
    feed_46(inputs, kOutputs, kMemory);
    feed_47(inputs, kOutputs, kMemory);
    feed_48(inputs, kOutputs, kMemory);
    feed_49(inputs, kOutputs, kMemory);
    feed_50(inputs, kOutputs, kMemory);
    feed_51(inputs, kOutputs, kMemory);
    feed_52(inputs, kOutputs, kMemory);
    feed_53(inputs, kOutputs, kMemory);
    feed_54(inputs, kOutputs, kMemory);
    feed_55(inputs, kOutputs, kMemory);
    feed_56(inputs, kOutputs, kMemory);
    feed_57(inputs, kOutputs, kMemory);
    feed_58(inputs, kOutputs, kMemory);
    feed_59(inputs, kOutputs, kMemory);
    feed_60(inputs, kOutputs, kMemory);
    feed_61(inputs, kOutputs, kMemory);
    feed_62(inputs, kOutputs, kMemory);
    feed_63(inputs, kOutputs, kMemory);
    feed_64(inputs, kOutputs, kMemory);
    feed_65(inputs, kOutputs, kMemory);
    feed_66(inputs, kOutputs, kMemory);
    feed_67(inputs, kOutputs, kMemory);
    feed_68(inputs, kOutputs, kMemory);
    feed_69(inputs, kOutputs, kMemory);
}

inline void GoDeeperTrain(const float rate, const float *targets)
{
    train_0(&rate, targets, kMemory);
    train_1(&rate, targets, kMemory);
    train_2(&rate, targets, kMemory);
    train_3(&rate, targets, kMemory);
    train_4(&rate, targets, kMemory);
    train_5(&rate, targets, kMemory);
    train_6(&rate, targets, kMemory);
    train_7(&rate, targets, kMemory);
    train_8(&rate, targets, kMemory);
    train_9(&rate, targets, kMemory);
    train_10(&rate, targets, kMemory);
    train_11(&rate, targets, kMemory);
    train_12(&rate, targets, kMemory);
    train_13(&rate, targets, kMemory);
    train_14(&rate, targets, kMemory);
    train_15(&rate, targets, kMemory);
    train_16(&rate, targets, kMemory);
    train_17(&rate, targets, kMemory);
    train_18(&rate, targets, kMemory);
    train_19(&rate, targets, kMemory);
    train_20(&rate, targets, kMemory);
    train_21(&rate, targets, kMemory);
    train_22(&rate, targets, kMemory);
    train_23(&rate, targets, kMemory);
    train_24(&rate, targets, kMemory);
    train_25(&rate, targets, kMemory);
    train_26(&rate, targets, kMemory);
    train_27(&rate, targets, kMemory);
    train_28(&rate, targets, kMemory);
    train_29(&rate, targets, kMemory);
    train_30(&rate, targets, kMemory);
    train_31(&rate, targets, kMemory);
    train_32(&rate, targets, kMemory);
    train_33(&rate, targets, kMemory);
    train_34(&rate, targets, kMemory);
    train_35(&rate, targets, kMemory);
    train_36(&rate, targets, kMemory);
    train_37(&rate, targets, kMemory);
    train_38(&rate, targets, kMemory);
    train_39(&rate, targets, kMemory);
    train_40(&rate, targets, kMemory);
    train_41(&rate, targets, kMemory);
    train_42(&rate, targets, kMemory);
    train_43(&rate, targets, kMemory);
    train_44(&rate, targets, kMemory);
    train_45(&rate, targets, kMemory);
    train_46(&rate, targets, kMemory);
    train_47(&rate, targets, kMemory);
    train_48(&rate, targets, kMemory);
    train_49(&rate, targets, kMemory);
    train_50(&rate, targets, kMemory);
    train_51(&rate, targets, kMemory);
    train_52(&rate, targets, kMemory);
    train_53(&rate, targets, kMemory);
    train_54(&rate, targets, kMemory);
    train_55(&rate, targets, kMemory);
    train_56(&rate, targets, kMemory);
    train_57(&rate, targets, kMemory);
    train_58(&rate, targets, kMemory);
    train_59(&rate, targets, kMemory);
    train_60(&rate, targets, kMemory);
    train_61(&rate, targets, kMemory);
    train_62(&rate, targets, kMemory);
    train_63(&rate, targets, kMemory);
    train_64(&rate, targets, kMemory);
    train_65(&rate, targets, kMemory);
    train_66(&rate, targets, kMemory);
    train_67(&rate, targets, kMemory);
    train_68(&rate, targets, kMemory);
    train_69(&rate, targets, kMemory);
    train_70(&rate, targets, kMemory);
}

#endif //TINYRNN_STANDALONE_GUARD_d6b80c7dd9ae4f1e887fe064c13ec7d32840a49a15066a4f58d40a912a2f7bb3
